### ISSUE TITLE
as a user I have a quick access to a running process from within the corresponding device

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/REACTor#113]
Wherever you are in the device, it would be nic to have a widget/tab whatever that you can click on and it brings you to the running process. This was not a feature requested by customers or Jan, but I often thought myself it would come handy. No visual guidelines are provided, complete freedom. Because it is a request by me, it's of low prio.

**Comment by DanielSeehausen** [comment]
perhaps considered closed by our go straight to running process option?
Otherwise, we now have clear visual indicators for which process is running from the device view, which seems to resolve this as its also a one click go to
