### ISSUE TITLE
As a user I need to know what are doing the buttons in the app.

### ISSUE THREAD

**Issue by petros751** [ospin-web-dev/REACTor#129]
We need to have "label" as a tooltip for each button to explain to the user what this button doing.
For example:
In the process builder we have a trash button and the button to add new phase are must have a tooltip that explain the following: "**Delete the phase**" and "**Add new phase**".
![27 08 2019_16 02 28_REC](https://user-images.githubusercontent.com/26736257/63773785-920dfe00-c8e4-11e9-9f65-64e904a03bce.png)

The buttons that they need "label":
Processes page:
1. trash button - "Delete process"

Process builder page:
1. trash button - "Delete phase"
2. edit button - "Edit phase name"
3. add phase button - "Add new phase"
4. save button - "Save the phase"
5.start button - "Start the process"

**Comment by vdiezel** [comment]
I'll close this. Buttons should be designed in a way that they don't rely on additional popup information
