### ISSUE TITLE
@petros751 deploy environment spike and webdev proposal

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#162]
@petros751 is looking into subdomain deployment options, with the goal of enabling non-blocking branch testing.

Sharing findings and implementation proposal Wednesday morning after stand up.

Please include:

- >= two potential solutions that integrate with our existing AWS hosted environment
- an architecture/implementation strategy that a developer would need to undertake to complete the plan
- a description of what the developer user flow would look like, and how it may [incorporate into our existing development workflow](https://github.com/ospin-web-dev/reactor/wiki)

**Comment by petros751** [comment]
I have set up in the netlify platform the REACTor repository. It's working. I have to found out how can we change the url subdomain from netlify and add the name of the branch as a netlify subdomain.
