### ISSUE TITLE
add device descriptions to the device card

### ISSUE THREAD

**Issue by petros751** [ospin-web-dev/REACTor#167]
Find a way to add a device descriptions in the bottom of the card as a:

- By who running the device?
- The name of the process that is running?
- In which phase it is?
- Started at?

![10 09 2019_18 38 29_REC](https://user-images.githubusercontent.com/26736257/64629045-24d98d00-d3fb-11e9-9f7f-6cdc2e612469.png)

**Comment by vdiezel** [comment]
We have implemented this already!
