### ISSUE TITLE
Reactor#162 deploy environment spike and webdev proposal

### ISSUE THREAD

**Issue by petros751** [ospin-web-dev/REACTor#176]
#162  I set up the github REACTor repository into netlify platform.

**Comment by petros751** [comment]
I have to found out how can we change the url subdomain from netlify and add the name of the branch as a netlify subdomain.

**Comment by petros751** [comment]
https://www.netlify.com/docs/custom-domains/ if you scroll down in this page you will see the **Branch Subdomain** topic @vdiezel

**Comment by DanielSeehausen** [comment]
I am going to close this as a duplicate of #162 !
Unless I am mistaken @petros751 , this seems to be all present in the other issue. 
Re-open and let me know if I have made a mistake please!
