### ISSUE TITLE
Nothing just test:)

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/REACTor#247]
All information you provide is _extremely_ helpful to us! Thank you for taking the time.

**Describe the bug**

**To Reproduce**
_(providing device and process IDs is very helpful when applicable! You can find them in the url)_

**Expected behavior**

**Screenshots**
(an easy way to do this is to make sure an image is copied to clipboard, then you can just `ctrl + v` right in line here and GitHub will do the rest!)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [ ] Production (https://ospin-app.com)

**Additional context**

**Comment by vdiezel** [comment]
@aahmed2021 we hope this template is helpful!
