### ISSUE TITLE
Provide opt in solution for the data viewer

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/REACTor#259]
# Current Behaviour
When a user opens up the data viewer, we load graphs for all upstream, even though the user is often not interested in most of them

# Desired Behaviour
Make the user opt in into the graphs he actually wants to see. This keeps things more organized and loads much faster. Also reduces our load on the AWS lambda big time. The graphs to be displayed need to be saved on process level but configurable defaults have to be saved on device level

**Comment by DanielSeehausen** [comment]
resolved by folding!
