### ISSUE TITLE
Spike: FU Feature Request - PID parameter

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#263]
Is this something we actually want to implement? Would it be good for everyone, or only for this user?

"
Zur Einstellung der PID-Parameter fände ich es gut (aber da bin ich vielleicht der einzige), wenn man die aktuellen P, I und D-Werte sehen könnte.
"

[please move to in progress then to completed once finished](https://trello.com/c/q8MvNyzc/40-show-pid-parameters-set-in-the-process)

**Comment by vdiezel** [comment]
It dawned on me that he simply wants to see the default controller values (either the ones provided by the firmware or the customer set ones)
