### ISSUE TITLE
Spike - FU bug report

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#264]
action required: where is work to be done? firmware or web dev?

[update this ticket once we know what work is being done where](https://trello.com/c/tiHkFdsD/33-calibration-if-the-user-calibrate-a-sensor-part-of-a-controller-then-the-controller-does-not-work-with-the-right-sensor-value-si)

"Calibration: if the user calibrate a sensor part of a controller, then the controller does not work with the right sensor value, since the calibrations factor are added only in the UI. Example: if I calibrate a sensor to be 39 instead of 37 but I do not communicate to the firmware that the new value is 39, then the controller wouldn't do anything because it would think the temperature is 37, as the target value."

from marcus:
"Ich habe im aktuellen Lauf die neue „Offset“-Kalibrierung genutzt (die Heizplatte hatte eine Temperatur von 39.3 Grad, bei eingestellten 37°C). Die Kurve verschiebt sich nun um den richtigen Wert, aber der Controller versucht nicht auf den richtigen Wert zu steuern. Heißt: die Platte ist zwar auf 37°C eingestellt, heizt aber nach der Kalibrierung auf 39.3 hoch. Gleiches gilt für pH, Heating, ..."

**Comment by vdiezel** [comment]
To contact firmware

**Comment by vdiezel** [comment]
Requested clarificaiton from firmware people - pending!

**Comment by vdiezel** [comment]
Fimrware (Tim) confirmed it is an issue on their side.
