### ISSUE TITLE
have to click twice on `request ssh` button

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#265]
![image](https://user-images.githubusercontent.com/17087405/68124390-8f94d980-ff0f-11e9-9d1b-a67c0e42fca0.png)

ali pointed out that we have to click the request ssh connection button twice. I believe this is a bug on our end and not firmware. I would confirm by checking the IoT subscribed messages.

**Comment by vdiezel** [comment]
Investigate cause of the issue that mqtt message seem to be published frequently: Firmware or webapp?
