### ISSUE TITLE
Cannot access a device that has been shared with user

### ISSUE THREAD

**Issue by Tim-OS** [ospin-web-dev/REACTor#266]
All information you provide is _extremely_ helpful to us! Thank you for taking the time.

**Describe the bug**
A device has been shared with a user but it does not appear in the devices list

**To Reproduce**
1. Go to 'ospin-app.com'
2. Login with an account (eg. tpotie) 
3. Go to Devices page. "Berlin" Bioreactor does not appear

**Expected behavior**
"Berlin" Bioreactor to appear and to be able to access it.

**Screenshots**
The "tpotie" user was added (Screenshot from another account showing the access list)

![image](https://user-images.githubusercontent.com/48010639/68206285-b107cb00-ffcc-11e9-8892-ef18078512d5.png)

The Bioreactor can be accessed directly with the URL (but does not appear in the list)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [x] Production (https://ospin-app.com)

**DeviceID / ProcessID (if applies)**
The IDs can be found in the browser in the url: `ospin-app.com/device/46a5504b-0438-4757-a1d9-06ae0e73fbec`

**Additional context**
-

**Comment by DanielSeehausen** [comment]
fixed! this was a problem with deps on our end while working on the api v2
