### ISSUE TITLE
as a developer, I can deploy a specific branch to the hosted AWS **development** environment from the command line

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#34]
sounds like this is going to be straight forward with the `aws` global npm package (per @vdiezel). Should be an easy 3 pointer :)).

Perhaps we abstract the command into the `package.json` of hambda so new devs don't need the overhead, (unless its even easier...then maybe we just add instruction in the readme? or just share it?)

**Comment by vdiezel** [comment]
We are going to use the AWS-CLI here to ship our client to S3. I've created the docs in confluence for that here:
http://orwell:8099/display/WAT/Web+Client%3A+REACTor
