### ISSUE TITLE
waiting on the process view ends up throwing an error - see screenshot

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#340]
after a certain amount of time, just sitting on a non-running process screen throws this error. I have never seen it occur directly - only when I have left the tab and come back to it do I see this. Some investigation re: how long it actually takes and confirmation that's the screen that is the culprit is required!

![image](https://user-images.githubusercontent.com/17087405/69743624-086a0880-113f-11ea-8e1d-9538f04a13b1.png)

**Comment by O-Susanoo** [comment]
Steps to reproduce

1- Open two tabs of the app
2- Go to the second one start a new process
3- Go back to your first Tab (Abracadabra you have your error)

Now that i have seen it i will try to fix it and also understand why it wasn't caught by the error page

**Comment by O-Susanoo** [comment]
For info it's normal the error boundary can't catch those type of errors for the same reason this code doesn't catch 
`
try {
  setTimeout(_ => { throw new Error('Some problem in async land') }, 0)
} catch (err) {
  console.log('Logging error', err, info)
}
`
