### ISSUE TITLE
Month display for running processes in process widget (created on) and device widget (started on) are of by one

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/REACTor#351]
![bug_2](https://user-images.githubusercontent.com/37934155/70052727-31254e80-15d4-11ea-9980-2f74aea5d13c.png)

January starts at index 0 in JS, december is 11 when parsed from the date. thats probably the source of this bug

**Comment by O-Susanoo** [comment]
Indeed Well done i have fixed it (getMonth function start from 0)

**Comment by DanielSeehausen** [comment]
have we never noticed the date was off by a whole month before now?
