### ISSUE TITLE
Provide a 404 when a user tries to access a resource that doesnt exists

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/REACTor#360]
e.g. when a user changes the deviceId in the url and reloads, we get our 500 error screen showing up and the error is being reported to our client error API. We shoudl provide a 404 and not report anything instead.

add 404 ospin page just like we have OOPSIN

**Comment by DanielSeehausen** [comment]
are we deferring instead to using the flash notifications now for this kind of stuff?
