### ISSUE TITLE
Additional Flash Notifications 

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#389]
(bumped this from a 1 to a two now that additional ones are being added)

- [x] confirm process started (green?)
- [x] process ended naturally (green?)
- [ ] ~~confirm ad-hoc change has been effected (green?)~~
- [x] Phase transitions (blue?)

- [x] confirm process stopped prematurely/by user (red?)

what do you guys think?

**Comment by O-Susanoo** [comment]
Green is usually when an action is successful , most of what you listed above is an action except the Phase transitions i see it more like an information so i would think it deserve a blue but one also can think of it as an action so your call

**Comment by DanielSeehausen** [comment]
I agree - I initially had it as blue but switched it after second guessing myself. seeing as blue was your first choice as well I'll go for blue

**Comment by vdiezel** [comment]
1. ok
2. Already implemeted
3. This one will be tricky because the device never confirms that it received the changes if I recall correctly. 
4. ok
5. This one will require some logic!

**Comment by DanielSeehausen** [comment]
i'm going to leave 3 out then to keep things simple for now!
