### ISSUE TITLE
Th units in some graphs are not shown

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/REACTor#396]
All information you provide is _extremely_ helpful to us! Thank you for taking the time.

Actually I talked with Nina and Dennis, Dennis will change the units in the Firmware

**Describe the bug**
-	All Heaters, including the heating plate
-	All Fans
-	Glucose value
-	Lactate value
-	Metabolite temperature value
-	Ph value
-	the name of po2 grahp is not correct

**To Reproduce**
see any finished process

**Expected behavior**
-	All Heaters, including the heating plate: percent [%]
-	All Fans: percent [%]
-	Glucose value : [mMol]
-	Lactate value: [mMol]
-	Metabolite temperature value: [°C]
-	Ph value: [-]
-	the name of po2 grahp should: Oxygen Saturation

**Screenshots**
![image](https://user-images.githubusercontent.com/56728314/70618178-81269580-1c12-11ea-900b-3a0ff61540a2.png)
![image](https://user-images.githubusercontent.com/56728314/70619254-ee3b2a80-1c14-11ea-8661-d917bd1295a2.png)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [ x ] Production (https://ospin-app.com)

**Comment by vdiezel** [comment]
solved by firmware engineers.
