### ISSUE TITLE
Ad hoc changes don't work properly while a process is paused

### ISSUE THREAD

**Issue by jansaam** [ospin-web-dev/REACTor#461]
```diff
! I have not been able to recreate this ticket. Celltainer is a poor testing device right now though, so I will try again once we have access to another device. 
! waiting to point until I can reproduce
```

**To recreate:**
- Create and start new process
- pause process
- do an ad hoc change (unclear if this means persist ad hoc changed or not) in the current phase 
- user reported that the UI plays along - assume this means they persisted and it appears to be changed, but it could be that nothing was persisted
- start the process and see the change was not effective
- reported this to be easily reproduce-able by changing pump speed

**Expected behavior**
Ad hoc changes work in paused processes the same as in running ones

**Comment by DanielSeehausen** [comment]
I am going to jump on this now. I will start by investigating whether this is a user accepting changes or not issue. If it is, this should still be a ticket (perhaps not a bug), in which we beef up the UI so there is less user confusion. 

If that is not the issue, it appears ad-hoc changes for a paused process or not persisted, even though they say they are.

**Comment by vdiezel** [comment]
While working on unit conversion I saw that changes were persisted, even when the changes were not comitted by the user. MAy have contributed to the issue.
