### ISSUE TITLE
The owner of a device should be able to see all processes - clarify what the roles mean

### ISSUE THREAD

**Issue by jansaam** [ospin-web-dev/REACTor#462]
**Description**
currently i can only see processes that someone explicitly shared with me. In case I have higher right to the device I would expect to also have at least the same rights on processes.
Generally it is unclear which rights I have as the owner of a machine. 

- Is there a role that superseed all others? 
- Who can take the ownership role away from other users? 
- And what does the little crown in the access table mean?
- Who can see the admin tools such as the ssh access?

**Comment by DanielSeehausen** [comment]
Going to break this into two units of work now

**Comment by DanielSeehausen** [comment]
@jansaam this has been broken down into the following two tickets and I will be closing this one. 

#464 
#465 

Thanks for the report!
