### ISSUE TITLE
Configurator problem when there are too many phases in a process

### ISSUE THREAD

**Issue by jmoralesdalmau** [ospin-web-dev/REACTor#471]
When a process has a lot of phases, the configurator feature in the UI is not properly working.

![configurator_problem](https://user-images.githubusercontent.com/58782447/72514095-543b5300-384e-11ea-82b1-9f9040ee98e6.PNG)

You can see phases are out of the UI and there is not lateral scroll for instance, that could solve that.

**Comment by DanielSeehausen** [comment]
Issue seems to have returned :(

Minor example:

![image](https://user-images.githubusercontent.com/17087405/73838990-36da2300-4815-11ea-95f1-6e82f1f72441.png)

**Comment by vdiezel** [comment]
fixed again and hopefully for good.

**Comment by jmoralesdalmau** [comment]
:DDr. Jordi Morales DalmauOSPIN Project Managerwww.ospin.deEl dia 6 de febr. 2020 15:05, Viktor Diezel <notifications@github.com> va escriure:fixed again and hopefully for good.
