### ISSUE TITLE
Process view option dropdown clickability

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#509]
![image](https://user-images.githubusercontent.com/17087405/73838763-ba474480-4814-11ea-8584-71be82c40c80.png)

as a user, currently, I can only activate this dropdown if hovering over an internal element that encapsulates 'Table ' and the down arrow. 

As a user, if I am hovering anywhere inside the dropdown button tile, my cursor changes to the hand thing and I can activate the dropdown.

**Comment by ConorTighe1995** [comment]
BONUS! we are gonna fix this too
![ospin-bug](https://user-images.githubusercontent.com/9091759/75673407-cb9c3900-5c7a-11ea-9b24-59da6db1a6c5.png)

**Comment by ConorTighe1995** [comment]
I fixed the notification bug in commit 8fe0adf543d7fc17e195905ce916aac0ab8e638a as part of the 509-dropdown-click-bounds branch.
