### ISSUE TITLE
Process Access Checkboxes View

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#558]
Currently, we use checkboxes in the process access view. This view is accessible through a process tile (hover over the tile and it is one of the little circles).

These display after a user has selected `Group`, and are used to communicate the permissioning levels of a given group:

![image](https://user-images.githubusercontent.com/17087405/75673536-79134a80-5c83-11ea-992d-4b6c7f4ae7b4.png)

While working with Jordi and Lina, they found them misleading, doubly so because the cursor changes to a selectable mouse when over them. Being non-selectable, we thought it best to move away from checkboxes if possible (or, at a minimum, keep the cursor from changing to a finger pointer thing).

A potential way to take this is something like this (but better positioned, and maybe bold):

![image](https://user-images.githubusercontent.com/17087405/75673787-0787cc00-5c84-11ea-944f-988e42be6574.png)

Consider possible solutions that are UI friendly and
![image](https://user-images.githubusercontent.com/17087405/75673822-1bcbc900-5c84-11ea-9e0d-ffe61064ecce.png)it

**Comment by vdiezel** [comment]
has been closed here:https://github.com/ospin-web-dev/REACTor/pull/590
