### ISSUE TITLE
the transition method (duration) seems not working in the celltainer

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/REACTor#575]
**Describe the bug**
in a running process i added tow phases, the duration of one was 4 h and the next was manual. the phase with 4h still working the hole night and i must stopped manually.

**To Reproduce**

https://ospin-app.com/device/9ef4f0b3-977b-4d36-9760-bba0b789bb0c/process/f760f6bd-2da2-44ef-978e-78b9ad14c514

**Expected behavior**
change the phases automatically 

**Screenshots**
![image](https://user-images.githubusercontent.com/56728314/76075817-f699cc00-5f9d-11ea-913a-9e991acef2ba.png)
![Chart (20)](https://user-images.githubusercontent.com/56728314/76075853-04e7e800-5f9e-11ea-8377-73050cf898f4.jpeg)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [ x] Production (https://ospin-app.com)

**DeviceID / ProcessID (if applies)**
https://ospin-app.com/device/9ef4f0b3-977b-4d36-9760-bba0b789bb0c/process/f760f6bd-2da2-44ef-978e-78b9ad14c514

**Additional context**

**Comment by DanielSeehausen** [comment]
I believe this was a device Error. I checked all logs. No errors on our end. 
The device never registered an auto phase change trigger
