### ISSUE TITLE
OOPSIN errors in prod are not reporting

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#576]
### Deliverable
- Ensure OOPSIN errors in prod get reported through hambda and propagated to slack

### Info
Something is wrong in our chain of:

- Error happens on prod
- OOPSIN page gets displays (this is confirmed to be working)
- The error gets reported through Hambda (this seems not to be working)
- The error gets propagated to slack (definitely not working :O )

After seeing the OOPSIN, I got this out of console:
![image](https://user-images.githubusercontent.com/17087405/76077607-50e85c00-5fa1-11ea-9f8b-c5bf7e0910b5.png)

This ticket _might_ have been solved when master got Utils service re-deployed, because there was a failing reference to Logger:

![image](https://user-images.githubusercontent.com/17087405/76079152-5c895200-5fa4-11ea-81ab-473531c4736c.png)

fixed by this: https://github.com/ospin-web-dev/hambda/pull/284

(And before that issue, there was a different error)

**Comment by vdiezel** [comment]
has been fixed !
