### ISSUE TITLE
the process and phase Overview is failed

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/REACTor#608]
All information you provide is _extremely_ helpful to us! Thank you for taking the time.

**Describe the bug**
the process and phase Overview is failed, i can only see the live data

**To Reproduce**
1. Go to 'Celltainer'
2. Click on 'the running process'
3. Scroll down to 'any graph'
4.klick in process button on the graph
5. see the error: it doesn't change anything
6. if i choose  specific phase, the UI is shown: No data found
_(providing device and process IDs is very helpful when applicable! You can find them in the url)_

**Expected behavior**

**Screenshots**
(an easy way to do this is to make sure an image is copied to clipboard, then you can just `ctrl + v` right in line here and GitHub will do the rest!)
![image](https://user-images.githubusercontent.com/56728314/77299009-19411a00-6cec-11ea-9eda-7b16a2105ccb.png)

**Environment**
 - [ ] Development (https://dev.ospin-app.com)
 - [x ] Production (https://ospin-app.com)

**DeviceID / ProcessID (if applies)**
https://ospin-app.com/device/9ef4f0b3-977b-4d36-9760-bba0b789bb0c/process/d0e73831-994c-4beb-9033-1fddb7155347

**Additional context**

**Comment by vdiezel** [comment]
It was my fault and it works again.

**Comment by aahmed2021** [comment]
thank you Viktor
