### ISSUE TITLE
BREAK ME UP Ideation one-click-process

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/REACTor#611]
One-click-process is a feature that will allow authorized people on a device to create processes that can be only viewed and executed by a person of lower authorization level. On-clickable processes should also be visually distinguishable. 

This is a way how we can achieve this with minimum new features. 

## STEPS

  1. For visual organization a pinning feature could be implemented. This feature should be 
      implemented independently from the one-click-process because this is of value for every 
      customer as several of them asked for a way of organizing their processes. 

      Alternative: Allow tagging / labelling processes!

      __Tickets__: 
                   - UI for setting lables / pinning
                   - UI for displaying pinned processes / filtering by labels etc..
                   - Update backend to make the new process properties persistent

  2. Authorization: the trickiest part

     The correct authorization is required on a.) the device and b.) the process template and c.) on the process clone created from the template

     For the device, the user should be able to view processes (VIEW bit) and execute (EXECUTE bit) the one they have the authorization for. Luckily, the operator group on devices does exactly this!
(Double check if an operators can actually create processes - if so, forbid it!)

     For the process template (which is just a normal process but used as a term for better understanding here) the user shoud have only VIEW access to it - we have the viewers group for this.

     For the executable process derived from the template the user needs VIEW and EXECUTE rights, unfortunately we don't have a group for this, as the operators group on processes also contains the EDIT bit. So a new group needs to be created here.

     Sharing the process is necessary to share the process that should serve as a template with the user who should execute it. The process template is shared with the operator putting them into the viewers group on the process. 

     Alternative: One-clickable-processes are visible by every user on the device -  thats a much more work but you could skip th sharing step then.

     Because the user would need the EDIT bit set to be able to clone the process, he can't do it yet.

     The way to grant the user access to create an executable process with the desired authorization could be this. 

     Create a new property on the processes - lets call it one-clickable which can be set by anybody who has EDIT rights on the process. It allows calling a new endpoint that does the same thing as the clone process deal, but adds the user who clones it only as a member in the newly created group on the new process, instead of making him the owner. The owner remains the same (?). Should the the processId of the new process be added to the originator of the process template? The Authorization required for this endpoint would be: You have to have the 'EXECUTE' bit set on the device you triy to call this endpoint on. The backend also needs to assert the the endpoint is called on a 'one-clickable' process.

     __Tickets__: 
                  - UI for making a process one-clickable
                  - UI for calling the new new endpoint on a shared template including redirection to the 
                    process builder with the newly created process loaded
                  - Implement the new endpoint for the described cloning alternative which adds the user to a new group which has only EXECUTE and VIEW rights
   
## The full flow would be this

The new user is added by somebody with the correct authorization on the device as an `operator` to the device. The process template creator shares the process template with the new user, putting him into the viewers group. Now the process template creator sets the one-click flag on the 
 template, which allows the operator to call the new endpoint which will crate a clone of the template and add them to a new group (which needs to be created first) with VIEW and OPERATE rights on the process. 

When calling it, the UI creates a the new process (or adds the new process being returned from the backend) for the user, and redirects him to the process builder in the same manner the CreatesProcess modal does. There the user can simply start the process. So it is really a 'two-click-process' , maybe three if we want a confirmation when a user requests a clone from the template.
Tagging or pinning would simply position the template at an easily accessible spot

---------------------------------------------

## AFTERMATH

For the sake of completeness, the newly created group should also be available as an option in the modal for sharing a process. It is not necessary for completing this feature because the new group is only used here on the cloned process, not the shared process. 

Because our backend currently only supports adding users to the default groups, a migratiion strategy is needed.

Create tickets for this!

**Comment by DanielSeehausen** [comment]
admin
slave

admin shared device to slave: operator
admin makes oneClick process
admin shares oneClick process to slave: viewer

**Comment by DanielSeehausen** [comment]
# Pinning

### REACTor

#### Process Widget Status Overhaul
  - [ ] Update process icons (4 in total) color and icon appropriate for status
    - Green executable color should match green on device online
    - Finished process color required (use current grey of icon)
    - Process Paused Symbol required (double line)
  - [ ] Remove status text from process widgets (see image)
  - [ ] remove line separating the revealable circle icons and rest of widget
  - [ ] display all icons justified left, except for delete, which is justified right
  - [ ] delete icon becomes same trash icon as the delete phase trash icon (see image)

![image](https://user-images.githubusercontent.com/17087405/77420186-e2d9cc80-6dc9-11ea-91e8-d1cce89b1db8.png)

![image](https://user-images.githubusercontent.com/17087405/77421281-d22a5600-6dcb-11ea-8a77-ad7c5633cfa7.png)

---

#### UI for setting process as pinned

As a user, when I hover over a process widget, I see an icon that I recognize as 'pinning'. When I click this icon, I see the process automatically move directly after the 'Build Process' icon, OR if there are already pinned process(es) present, it moves to its respective place in chronological order among the pinned processes, which are always the first group of process widgets after the 'Build Process'.

  - [ ] update the process object mapper to account for a `pinned` key boolean. if none is found, defaults to false
  - [ ] add grey icon to set a process as pinned (find appropriate pin icon - check semantic first)
  - [ ] when a user clicks this, the process object gets its `pinned` boolean toggled, and the icon receives a change in color when pinned vs. the normal icon grey when not pinned
  - [ ] update the processes display to always display pinned processes first (directly after the "Build Process" in the tile view, and as the top rows in the table view). This should be the role of the display or view, not the store. @vdiezel mentioned `Processes.jsx` might delegate a list to both the table and tile view, so the sorting should likely happen there! This is high priority for testing, at least given a collection of processes with some pinned, they are displaying in the appropriate order (and click testing on pinning if ambitious)
  - [ ] Pinned processes should always display their colored icon (not just on hover) when pinned is true
  - [ ] this should fire a call to update process in nexus with the process having the correct pinned status (to be turned on later - leave commented or inactive for now)

---

#### Update usage of operators and maintainers groups

- [ ] In object mapper for processes and everything related to access, duplicate the operators group as a maintainers group when it enters the client (TO BE REMOVED AFTER HAMBDA MIGRATION)
- [ ] Update operators groups to have 10100 access 
- [ ] Update maintainers groups to have 11100 access

---

### Hambda

#### Migrate process data to track `pinned`
- [ ] add `pinned: false` to all processes (dev + prod) via a script

---

#### Update backend for pinned processes
- [ ] update tests to pass in `pinned` booleans and more
- [ ] joi schema on update process needs to accept the new pinned key and restrict to boolean

---
---

# Permissioning Updates

### Hambda

#### Add new access group 'maintainers'

**for access groups**
- [ ] unify `createProcessGroups` and `createDeviceGroups` 
- [ ] update operators access group permissions to match device operators: 10100
- [ ] update any and all refs to operators within processes to be maintainers, (most likely mainly display test)

**DB: for all resources (devices/processes):**
  - [ ] add a new group to access objects called 'maintainers', which has the access rights of 11100

**DB for all processes:**
  - [ ] duplicate current operators users into the new access group called 'maintainers', which has the access rights of 11100, and has all users who were operators
  - [ ] remove all process operators users

Spike to check for corner cases! Update process tests that deal with operators to instead test maintainers!

---

### REACTor

#### Remove temporary object mapper for processes

- [ ] In object mapper for processes and everything related to access, remove the duplication of the operators group as a maintainers group when it enters the client


---

### General

Have a meeting with Nina to talk about this one click process stuff
