### ISSUE TITLE
DESTROY THE NEXUS

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#655]
(I snap assigned to @O-Susanoo as I assume he would get the most gratification out of any of us for destroying his no.1 rival)

### Description
The unanimous vote was: we can't stand the git submodule format as it is providing zero value and moderate headaches

---

### Deliverables
- MAKE THE MONOREPO A TRUE MONOREPO
- REACTOR CONSUMES NEXUS LIKE AN AMOEBA
- 🔫 / RETIRE THE NEXUS REPO!

---

### Additional context
Images for reference:
![image](https://user-images.githubusercontent.com/17087405/78654929-944a2900-78c5-11ea-90c6-de71cd23b42b.png)

![image](https://user-images.githubusercontent.com/17087405/78654880-83011c80-78c5-11ea-82a0-bf1ba8c80be2.png)

**Comment by O-Susanoo** [comment]
after this image who ever open a pr should add a john cena you can't see me image

![image](https://user-images.githubusercontent.com/57438770/78656193-f0f61580-78be-11ea-8751-f893e6b3c886.png)
