### ISSUE TITLE
memory leak in REACTor

### ISSUE THREAD

**Issue by O-Susanoo** [ospin-web-dev/REACTor#667]
If you have a running process and then go to dashboard you will see this

![image](https://user-images.githubusercontent.com/57438770/78903982-cdc09700-7a73-11ea-90a7-72dee48bace4.png)

For the record this ticket was grabbed at some point but i couldn't reproduce the issue since the error on the image says it's in the logging i tried to run a process and cause an event (pause the process, stop the process) to trigger logging but no luck i tried to add stream, remove stream again no luck , i also tried investigate from code side but nothing suspicious caught my eye

**Comment by vdiezel** [comment]
This issue seems to be fixed
