### ISSUE TITLE
reviewing a chart

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/REACTor#718]
All information you provide is helpful to us! Thank you for taking the time.

**Describe the bug**
When expanding collapsed graphs under certain circumstances, the viewport moves around and leads to a poor user experience.

**To Reproduce**
1. Go to 'celltainer device'
2. Go to a completed process that has data
3. Collapse all graphs
4. Open a group
5. Open the top stream graph in the group
6. Scroll your screen down and then open the bottom stream graph in the group
(the viewport will jerk upwards)

(if you can't recreate, ping daniel)

**Expected behavior**
When opening charts, the viewport shouldn't move it all

**Environment**
all environments!

**Comment by DanielSeehausen** [comment]
i will triage this asap
