### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by O-Susanoo** [ospin-web-dev/REACTor#720]
if the stream unit is rpm (lowercase) and one try to convert it will cause an issue because we only convert a stream unit if it's RPM , this is not visible now because RPM is never being used but as soon  as we will have other unit this issue will rise

we need to standardize either the way we store unit or the way we convert them

**Comment by vdiezel** [comment]
rpm should always be lowercase following this convention: 

https://en.wikipedia.org/wiki/Revolutions_per_minute

I think in most places it has been updated by the firmware engineers
