### ISSUE TITLE
R6: User demo account is cached and the changes they made persist after reload.

### ISSUE THREAD

**Issue by ConorTighe1995** [ospin-web-dev/REACTor#743]
### Feature Description / Problem Solved by Feature
As a user who has already started a demo OSPIN experience(tm), I can close or reload the browser at anytime and when I reload it (not in incognito), I am automatically authorized with the demo user that was already created for me, and I skip the landing/splash/start demo page and go straight to /devices

Validate that this works and demo accounts persist data after close.

BLOCKED BY #740
---

### Deliverables
As a user...
 - [x] I can close or reload the browser and still see my update uIConfig values, device/process changes, and any other changed data from the last session.

### Additional context
This will be heavily dependent on how the demo accounts are implemented.

**Comment by O-Susanoo** [comment]
this ticket is actually not needed because once a user is created and logged in nothing will be required
