### ISSUE TITLE
Check processes field in device object mapper is used

### ISSUE THREAD

**Issue by O-Susanoo** [ospin-web-dev/REACTor#748]
first - create a backend ticket to be completed **after** this ticket is completed (mark it as blocked by this ticket). The backend work should update update all references to device processes to find them through a processes (deviceId) query on an interface. 

in device object mapper it seem that we have a field called processes according to @vdiezel  this field should be deprecated , try to see if we can remove it 

And if you have time try to see if they are others fields with the same curse

--- 

this may be used here:
```
// LogViewQueryBar
   11   const userProcessesOnDevice = processes
   12     .filter(process => device.processes.includes(process.id))
   13     .map(process => ({ text: process.name, value: process.id, key: process.id }))   
```

**Comment by DanielSeehausen** [comment]
change the filter to work on the processes array instead of being derived from the device (in the code snippet above)
