### ISSUE TITLE
Device widget ordering non-deterministic

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/REACTor#785]
denis reported device widget order does not seem to be the same every time. Propose we order devices by:
Online > offline (where within online and offline we order by createdAt -1)

Here is the order between two different renders:

![image](https://user-images.githubusercontent.com/17087405/83637241-93710300-a5a7-11ea-933f-7ab2fd555309.png)
![image](https://user-images.githubusercontent.com/17087405/83637246-97048a00-a5a7-11ea-8d82-63a8cd46914a.png)

Please follow up with Denis on slack once this gets merged in and thank him for reporting

**Comment by vdiezel** [comment]
source of this error is that when a user refreshes the browser within a device view, this device is added first into the array. When a user load the devices view without having laoded a single device first, it sorts them in the order they arrive from the DB
